name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Pull and run Docker image on EC2
        run: |
          echo $(aws ecr get-login-password --region ap-south-1) | docker login --username AWS --password-stdin 470812156695.dkr.ecr.ap-south-1.amazonaws.com
          docker pull 470812156695.dkr.ecr.ap-south-1.amazonaws.com/node-next-app:latest
          docker run -d -p 3000:3000 -p 4000:4000 --name webapp 470812156695.dkr.ecr.ap-south-1.amazonaws.com/node-next-app:latest
